"""Integration tests for Task 14.2 auth wiring (mcp-common auth primitives).

These tests assert the wiring — not just the registration — so a future
regression that registers middleware but never installs it cannot pass
silently. Per ``mcp-surface-health-illusion.md``, a server that
registers auth components but never exercises them returns healthy
``/health`` while providing zero auth surface; the assertions below
ensure every layer is observable.

Each test uses a 32+-byte secret generated by ``secrets.token_urlsafe`` so
``AuthConfig``'s 32-char minimum is satisfied without falling back to
``BODAI_SHARED_SECRET`` (which would be a different secret every run and
break issuer pinning).
"""

from __future__ import annotations

import asyncio
import secrets
from datetime import UTC, datetime, timedelta
from typing import Any

import pytest

# Constant service_name used by every inline tool the test file builds.
# The current @require_auth decorator rejects an "unknown" service_name
# (I-R2-2 fix); we use the same value the runtime injects so the inline
# decorator can locate the principal it expects.
APP_NAME_FOR_TEST = "archive-org-mcp"


def _jwt_for_test(*, secret: str, audience: str = "archive-org-mcp") -> str:
    """Mint a short-lived JWT against the local test secret."""
    from mcp_common.auth.core import create_service_token
    from mcp_common.auth.permissions import Permission

    return create_service_token(
        secret=secret,
        issuer="test",
        audience=audience,
        permissions=[Permission.READ],
        subject="user-1",
        ttl_seconds=300,
    )


def _settings_with_auth(secret: str) -> Any:
    from archive_org_mcp.config.settings import ArchiveOrgSettings

    return ArchiveOrgSettings(
        auth_config={
            "enabled": True,
            "secret": secret,
            "trusted_issuers": ["test"],
            "identity_providers": {"jwt": {"type": "jwt"}},
        }
    )


@pytest.mark.integration
def test_invalid_bearer_token_is_rejected_by_middleware() -> None:
    """I-5 fix: the middleware rejects un-parseable Bearer tokens.

    Drives the middleware's ``_extract_bearer_token`` helper (the
    well-known entry point for token extraction). Full HTTP transport
    testing is deferred to the integration suite in mcp-common; here we
    assert the contract that garbage Authorization headers cannot
    silently bypass the middleware.
    """
    from archive_org_mcp.config.settings import ArchiveOrgSettings
    from archive_org_mcp.server import Runtime

    secret = secrets.token_urlsafe(48)
    settings = ArchiveOrgSettings(
        auth_config={
            "enabled": True,
            "secret": secret,
            "trusted_issuers": ["test"],
            "identity_providers": {"jwt": {"type": "jwt"}},
        }
    )
    runtime = Runtime(settings=settings)
    middleware = runtime._build_auth_middleware()
    assert middleware is not None

    from mcp_common.auth.middleware import _extract_bearer_token

    # No header -> None (anonymous allowed; tool decides).
    assert _extract_bearer_token({}) is None
    # Wrong scheme -> None.
    assert _extract_bearer_token({"authorization": "Basic dXNlcjpwYXNz"}) is None
    # Garbage payload -> not None (the middleware will then attempt
    # verify_token and raise AuthError).
    token = _extract_bearer_token({"authorization": "Bearer not-a-real-jwt"})
    assert token == "not-a-real-jwt"


@pytest.mark.integration
def test_authenticated_tool_call_reaches_tool_body() -> None:
    """I-5 fix: a tool call with a valid token reaches the tool body.

    We exercise the @require_auth path through a fresh inline tool rather
    than any of archive-org-mcp's domain tools (which carry their own
    permission gates independent of BearerTokenMiddleware).
    """
    from mcp_common.auth.context import seed_principal
    from mcp_common.auth.decorator import require_auth
    from mcp_common.auth.permissions import Permission
    from mcp_common.auth.principal import Principal

    @require_auth(permission=Permission.READ, service_name=APP_NAME_FOR_TEST)
    async def inline_protected_tool() -> str:
        return "tool body ran"

    principal = Principal(
        issuer="test",
        subject="user-1",
        permissions=frozenset({Permission.READ}),
        expires_at=datetime.now(UTC) + timedelta(hours=1),
        raw_claims={},
    )
    token_handle = seed_principal(principal)
    try:
        result = asyncio.run(inline_protected_tool())
        assert result == "tool body ran"
    finally:
        token_handle.var.reset(token_handle)


@pytest.mark.integration
def test_health_envelope_includes_auth_component_when_enabled() -> None:
    """Supplementary: /health surfaces the auth component when enabled."""
    from archive_org_mcp.server import create_app_sync

    secret = secrets.token_urlsafe(48)
    app = create_app_sync(settings=_settings_with_auth(secret))

    async def hit_health() -> dict[str, Any]:
        from httpx import ASGITransport, AsyncClient

        asgi = app.http_app()  # type: ignore[attr-defined]
        async with AsyncClient(
            transport=ASGITransport(app=asgi), base_url="http://test"
        ) as client:
            response = await client.get("/health")
            assert response.status_code == 200
            return response.json()

    body = asyncio.run(hit_health())
    names = [c["name"] for c in body.get("components", [])]
    assert "auth" in names, f"expected 'auth' in components, got {names!r}"


@pytest.mark.integration
def test_health_envelope_omits_auth_component_when_disabled() -> None:
    """Default (no auth_config) → /health does not surface auth component.

    Matches the ``mcp-surface-health-illusion`` guard: components[] must
    reflect what is actually wired, not what was once wired.
    """
    from archive_org_mcp.server import create_app_sync

    app = create_app_sync()

    async def hit_health() -> dict[str, Any]:
        from httpx import ASGITransport, AsyncClient

        asgi = app.http_app()  # type: ignore[attr-defined]
        async with AsyncClient(
            transport=ASGITransport(app=asgi), base_url="http://test"
        ) as client:
            response = await client.get("/health")
            assert response.status_code == 200
            return response.json()

    body = asyncio.run(hit_health())
    names = [c["name"] for c in body.get("components", [])]
    assert "auth" not in names, f"auth component leaked: {names!r}"


@pytest.mark.integration
def test_misconfigured_jwt_without_secret_raises_at_startup() -> None:
    """I-9 fix: auth.enabled with a JWT provider but no secret must fail loud.

    Without the I-9 guard, ``JWTIdentityProvider.__init__`` raises
    ``SecretNotConfiguredError`` on first request. With the guard, the
    failure surfaces at server construction time.
    """
    from archive_org_mcp.config.settings import ArchiveOrgSettings
    from archive_org_mcp.server import create_app_sync

    settings = ArchiveOrgSettings(
        auth_config={
            "enabled": True,
            "trusted_issuers": ["test"],
            "identity_providers": {"jwt": {"type": "jwt"}},
        }
    )

    with pytest.raises(RuntimeError, match="auth.secret is None"):
        create_app_sync(settings=settings)
